import { useMemo, useState } from 'react';
import { PageHeader } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import { Card } from '@/components/ui/Card';
import { useAsync, useMutation } from '@/hooks/useAsync';
import { notificationsService } from '@/services/notifications';
import { queryKeys } from '@/lib/queryClient';
import type { AppNotification, NotificationType } from '@/types/domain';
import { NotificationFilters, type NotificationFiltersValue } from '@/components/notifications/NotificationFilters';
import { NotificationItem } from '@/components/notifications/NotificationItem';
import { notificationMessage, notificationTitle } from '@/components/notifications/notificationMeta';

const DEFAULT_FILTERS: NotificationFiltersValue = {
  readStatus: 'ALL',
  type: 'ALL',
  search: '',
};

function matchesFilters(notification: AppNotification, filters: NotificationFiltersValue) {
  if (filters.readStatus === 'UNREAD' && notification.readAt) return false;
  if (filters.readStatus === 'READ' && !notification.readAt) return false;
  if (filters.type !== 'ALL' && notification.type !== filters.type) return false;

  const search = filters.search.trim().toLowerCase();
  if (!search) return true;

  return [
    notificationTitle(notification),
    notificationMessage(notification),
    notification.type,
    notification.relatedEntityType,
  ]
    .filter(Boolean)
    .some((value) => String(value).toLowerCase().includes(search));
}

const INVALIDATE_NOTIFICATIONS = [queryKeys.notifications, queryKeys.unreadNotifications];

export function NotificationsPage() {
  const notifications = useAsync(() => notificationsService.list(), [], { queryKey: queryKeys.notifications });
  const markRead = useMutation(notificationsService.markRead, { invalidateKeys: INVALIDATE_NOTIFICATIONS });
  const markAll = useMutation(notificationsService.markAllRead, { invalidateKeys: INVALIDATE_NOTIFICATIONS });
  const [filters, setFilters] = useState<NotificationFiltersValue>(DEFAULT_FILTERS);

  const notificationTypes = useMemo<NotificationType[]>(() => {
    const types = new Set((notifications.data ?? []).map((notification) => notification.type));
    return Array.from(types).sort();
  }, [notifications.data]);

  const filteredNotifications = useMemo(
    () => (notifications.data ?? []).filter((notification) => matchesFilters(notification, filters)),
    [filters, notifications.data],
  );

  const unreadCount = useMemo(
    () => (notifications.data ?? []).filter((notification) => !notification.readAt).length,
    [notifications.data],
  );

  return (
    <>
      <PageHeader
        title="Notifications"
        subtitle="Track system events generated by tasks, leads, approvals, invitations and reports."
        action={<Button variant="secondary" onClick={() => markAll.mutate()} loading={markAll.loading}>Mark all read</Button>}
      />

      <div className="notification-summary-grid">
        <Card className="metric-card">
          <span>Total notifications</span>
          <strong>{notifications.data?.length ?? 0}</strong>
        </Card>
        <Card className="metric-card">
          <span>Unread</span>
          <strong>{unreadCount}</strong>
        </Card>
        <Card className="metric-card">
          <span>Visible after filters</span>
          <strong>{filteredNotifications.length}</strong>
        </Card>
      </div>

      <NotificationFilters value={filters} notificationTypes={notificationTypes} onChange={setFilters} />

      <Card className="notifications-list-card">
        {notifications.loading ? <p className="muted">Loading notifications…</p> : null}
        {notifications.error ? (
          <div className="error-box">
            <strong>Could not load notifications.</strong>
            <p>{notifications.error}</p>
            <Button variant="secondary" size="sm" onClick={notifications.refetch}>Retry</Button>
          </div>
        ) : null}
        {!notifications.loading && !notifications.error && filteredNotifications.length === 0 ? (
          <div className="state-block">
            <strong>No notifications found</strong>
            <p className="muted">Try changing the filters or clearing the search field.</p>
          </div>
        ) : null}
        {filteredNotifications.map((notification) => (
          <NotificationItem
            key={notification.id}
            notification={notification}
            action={!notification.readAt ? (
              <Button variant="secondary" size="sm" loading={markRead.loading} onClick={() => markRead.mutate(notification.id)}>
                Mark read
              </Button>
            ) : null}
          />
        ))}
      </Card>
    </>
  );
}